project_id = "azfyktcspmhcaqbhozuw"

[functions.create-razorpay-order]
verify_jwt = false

[functions.fetch-order]
verify_jwt = false

[functions.neocortex-chat]
verify_jwt = false

[functions.verify-student]
verify_jwt = false

[functions.stream-video]
verify_jwt = false
