import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { content, imageBase64List } = await req.json();
    const results: { plagiarismDetected: boolean; aiImageDetected: boolean; stockImageDetected: boolean; details: string[] } = {
      plagiarismDetected: false,
      aiImageDetected: false,
      stockImageDetected: false,
      details: [],
    };

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // --- 1. Plagiarism check: compare content against recent posts ---
    if (content && content.trim().length > 20) {
      const { data: recentPosts } = await supabase
        .from("posts")
        .select("content")
        .order("created_at", { ascending: false })
        .limit(200);

      if (recentPosts && recentPosts.length > 0) {
        // Use AI to check if content is substantially similar to any existing post
        const existingSnippets = recentPosts
          .map((p: any) => p.content.slice(0, 300))
          .join("\n---\n");

        const plagiarismResp = await fetch(
          "https://ai.gateway.lovable.dev/v1/chat/completions",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${LOVABLE_API_KEY}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model: "google/gemini-2.5-flash-lite",
              messages: [
                {
                  role: "system",
                  content:
                    'You are a plagiarism detector. Compare the NEW POST against the EXISTING POSTS. If the new post copies or closely paraphrases (>60% similarity) any existing post, respond with JSON: {"plagiarized": true, "matchedSnippet": "..."}. Otherwise respond with {"plagiarized": false}. Respond ONLY with valid JSON.',
                },
                {
                  role: "user",
                  content: `NEW POST:\n${content.slice(0, 500)}\n\nEXISTING POSTS:\n${existingSnippets.slice(0, 3000)}`,
                },
              ],
            }),
          }
        );

        if (plagiarismResp.ok) {
          const plagiarismData = await plagiarismResp.json();
          const text = plagiarismData.choices?.[0]?.message?.content || "";
          try {
            const cleaned = text.replace(/```json\n?/g, "").replace(/```/g, "").trim();
            const parsed = JSON.parse(cleaned);
            if (parsed.plagiarized) {
              results.plagiarismDetected = true;
              results.details.push("Text content matches an existing post in the community.");
            }
          } catch {
            // If parsing fails, allow the post
          }
        }
      }
    }

    // --- 2. AI-generated image detection + Stock/Internet image detection ---
    if (imageBase64List && imageBase64List.length > 0) {
      for (let i = 0; i < imageBase64List.length; i++) {
        const imageData = imageBase64List[i];

        // Run AI-generated check and stock image check in parallel
        const [aiCheckResp, stockCheckResp] = await Promise.all([
          fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
            method: "POST",
            headers: {
              Authorization: `Bearer ${LOVABLE_API_KEY}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model: "google/gemini-2.5-flash",
              messages: [
                {
                  role: "system",
                  content:
                    'You are a strict AI-generated image detector specializing in fashion and design. Your job is to protect originality. Analyze the image and determine if it was generated by ANY AI tool — including but not limited to: Midjourney, DALL-E, Stable Diffusion, Google Gemini (Imagen), ChatGPT/GPT-4o/DALL-E 3, Claude, Adobe Firefly, Leonardo AI, Flux, Ideogram, Bing Image Creator, Meta AI, Apple Intelligence, Samsung Galaxy AI, or any other AI image generator. Look carefully for: unnaturally perfect lighting, overly smooth skin/surfaces, plastic-like textures, perfect symmetry, warped or missing fingers/hands/text, AI artifacts, unrealistic depth of field, hyper-clean backgrounds, repetitive micro-patterns, inconsistent reflections/shadows, too-perfect edges, watermark remnants, and any "uncanny valley" quality. Even if the image looks realistic, if it has ANY telltale signs of AI generation, flag it. When uncertain, lean toward flagging as AI-generated (err on the side of caution). Respond ONLY with valid JSON: {"ai_generated": true/false, "confidence": 0-100, "reason": "brief reason"}.',
                },
                {
                  role: "user",
                  content: [
                    { type: "text", text: "Is this image AI-generated? Analyze very carefully and strictly. Look for ANY signs of AI generation including perfect lighting, smooth textures, or uncanny qualities. If there is any doubt, flag it as AI-generated." },
                    { type: "image_url", image_url: { url: imageData } },
                  ],
                },
              ],
            }),
          }),
          fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
            method: "POST",
            headers: {
              Authorization: `Bearer ${LOVABLE_API_KEY}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model: "google/gemini-2.5-flash",
              messages: [
                {
                  role: "system",
                  content:
                    'You are a strict image originality detector for a fashion design student community. Your job is to determine if an image is ORIGINAL work (taken by the user themselves, their own sketch, their own design, their own garment photo) versus a DOWNLOADED/COPIED image from the internet. Flag the image as NOT original if it shows ANY of these signs: (1) Stock photography characteristics — professional studio lighting, generic poses, watermarks (even faint/removed ones), unnaturally high production quality for a student submission. (2) Screenshots from websites, apps, Pinterest, Instagram, Google Images — look for UI elements, browser chrome, social media overlays, cropping artifacts. (3) Professional fashion photography from magazines, lookbooks, runway shows, brand campaigns — these have distinctive editorial lighting, professional models, branded styling. (4) Famous or widely-circulated images — celebrity photos, viral images, memes, well-known artwork. (5) Product images from e-commerce sites — clean white backgrounds, multiple angles, price tags. (6) Images with EXIF-style compression artifacts suggesting multiple saves/downloads. (7) Images that look like they were taken from Google Image Search results. A genuine student submission would typically be: a phone photo of their own work, a scan of their sketch, a photo of fabric/garment they made, a selfie wearing their design, or a direct camera photo of their creative process. When uncertain, lean toward flagging as not original. Respond ONLY with valid JSON: {"is_original": true/false, "confidence": 0-100, "reason": "brief reason"}.',
                },
                {
                  role: "user",
                  content: [
                    { type: "text", text: "Is this image original student work or was it downloaded/copied from the internet? Look carefully for stock photo qualities, professional photography, screenshots, watermarks, or any sign this is not the student's own creation." },
                    { type: "image_url", image_url: { url: imageData } },
                  ],
                },
              ],
            }),
          }),
        ]);

        // Process AI-generated check
        if (aiCheckResp.ok) {
          const aiCheckData = await aiCheckResp.json();
          const text = aiCheckData.choices?.[0]?.message?.content || "";
          try {
            const cleaned = text.replace(/```json\n?/g, "").replace(/```/g, "").trim();
            const parsed = JSON.parse(cleaned);
            if (parsed.ai_generated && parsed.confidence >= 50) {
              results.aiImageDetected = true;
              results.details.push(
                `Image ${i + 1}: Detected as AI-generated (${parsed.confidence}% confidence). ${parsed.reason || ""}`
              );
            }
          } catch {
            // If parsing fails, allow the image
          }
        }

        // Process stock/internet image check
        if (stockCheckResp.ok) {
          const stockData = await stockCheckResp.json();
          const text = stockData.choices?.[0]?.message?.content || "";
          try {
            const cleaned = text.replace(/```json\n?/g, "").replace(/```/g, "").trim();
            const parsed = JSON.parse(cleaned);
            if (!parsed.is_original && parsed.confidence >= 50) {
              results.stockImageDetected = true;
              results.details.push(
                `Image ${i + 1}: Appears to be downloaded from the internet (${parsed.confidence}% confidence). ${parsed.reason || ""}`
              );
            }
          } catch {
            // If parsing fails, allow the image
          }
        }
      }
    }

    return new Response(JSON.stringify(results), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Originality check error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
